name: Build and Deploy on GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: Build
        run: |
          flutter pub get
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          allow_empty_commit: true
