name: Build and Deploy on GitHub Pages
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter and add it to the path.
      - name: Clone Flutter repository with master channel.
        uses: actions/checkout@v2
        with:
          repository: 'flutter/flutter'
          ref: 'master'
          path: 'flutter'
          fetch-depth: 0
      # - name: Add Flutter to the PATH.
      #   run: echo "::add-path::/$GITHUB_WORKSPACE/flutter/bin"
      # - name: Run Flutter doctor.
      #   run: flutter doctor -v
      - name: Enable Flutter web.
        run: flutter config --enable-web

      # Build Web Release
      - name: Get packages for the Flutter project.
        run: flutter pub get
      - name: Build
        run: |
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          allow_empty_commit: true
